version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements_dev.txt" }}
      - run:
          name: install
          command: |
            python3 -mvenv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_dev.txt" }}
      - run:
          name: test
          command: |
            . venv/bin/activate
            make test
      - store_artifacts:
          path: report.html
          destination: report.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
