version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install_and_test
          command: |
            python3 -mvenv venv
            . venv/bin/activate
            pip install .
            make test
      - store_artifacts:
          path: report.html
          destination: report.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
